version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_test_app
    ports:
      - "8080:80"  # Change to your preferred port
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: project_test_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Set your root password here
      MYSQL_DATABASE: your_database_name    # Your database name
      MYSQL_USER: your_username              # Your database username
      MYSQL_PASSWORD: your_password          # Your database user password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
