version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2023.08.1  # Using Ubuntu machine image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y zip unzip curl php8.2-cli php8.2-mbstring php8.2-xml php8.2-bcmath php8.2-zip
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install --no-dev --optimize-autoloader
      - run:
          name: Set Environment Variables
          command: |
            echo "APP_KEY=${APP_KEY}" >> .env

  deploy:
    machine:
      image: amazon/amazon-linux-2-x86_64
    steps:
      - run:
          name: Set up SSH
          command: |
            mkdir -p ~/.ssh
            echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H 98.81.168.142 >> ~/.ssh/known_hosts
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@98.81.168.142 "cd /var/www/html/laravel && composer install --no-dev --optimize-autoloader && php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
